services:
  db:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD : cartman
      POSTGRES_DB : postgres
    networks:
      - spring

  vocabulary:
    image: spring-project:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - spring

networks:
  spring:
    name: spring-compose