server:
  port : 8081

spring:
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: cartman
    password: cartman
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

logging:
  level:
    org.hibernate.tool.schema: TRACE

